CREATE TABLE Semesters(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    semester VARCHAR(10) NOT NULL,
    year INT NOT NULL,
    CHECK (semester IN ('fall', 'spring')),
    CHECK (year >= 2020 AND year < 9999),
    UNIQUE (semester, year)

);

CREATE TABLE AppConfig (
    config_id INT NOT NULL PRIMARY KEY DEFAULT 1,
    current_semester_id INT REFERENCES Semester(id)
);

CREATE TABLE Users (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    user_type VARCHAR(20) NOT NULL,

    -- typically for players only --
    joined_semester_id INT REFERENCES Semesters(id) ,
    jersey_num INT,

    -- duke users specific --
    duke_email VARCHAR(255) UNIQUE,

    -- external users specific --
    external_email VARCHAR(255) UNIQUE,
    hash_password TEXT,

    is_admin BOOLEAN DEFAULT FALSE,

    CHECK (user_type IN ('player', 'staff', 'alum')),
    CHECK (duke_email IS NOT NULL OR external_email IS NOT NULL)

);

CREATE TABLE Executives (
    executive_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INT NOT NULL REFERENCES Users(id),
    position VARCHAR(50) NOT NULL,
    term_start_year INT NOT NULL,
);

CREATE TABLE Staff (
    staff_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INT NOT NULL REFERENCES Users(id),
    staff_role VARCHAR(50) NOT NULL,
    active_semester_id INT NOT NULL REFERENCES Semesters(id),
);

CREATE TABLE Events (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    semester_id INT NOT NULL REFERENCES Semesters(id),
    location_name VARCHAR(255),
    location_address VARCHAR(255),
    category VARCHAR(30) NOT NULL,
    start_datetime TIMESTAMP,
    end_datetime TIMESTAMP,
    created_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    created_by INT REFERENCES Users(id),

    CHECK (category IN ('practice', 'tournament', 'game', 'other'))
    -- game refers to a standalone game --
);

CREATE TABLE UserAvailability (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    semester_id INT NOT NULL REFERENCES Semesters(id),
    user_id INT NOT NULL REFERENCES Users(id),
    day_of_week VARCHAR(10) NOT NULL,
    start_time TIME WITHOUT TIME ZONE NOT NULL,
    end_time TIME WITHOUT TIME ZONE NOT NULL,
    last_updated TIMESTAMP WITHOUT TIME ZONE DEFAULT (current_timestamp AT TIME ZONE 'UTC'),


    CHECK (day_of_week IN ('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday')),
    CHECK (start_time < end_time),
    UNIQUE (semester_id, user_id, day_of_week, start_time, end_time)
);

CREATE TABLE Polls (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    event_id INT NOT NULL REFERENCES Events(id),
    title VARCHAR(255),
    created_time TIMESTAMP WITHOUT TIME ZONE DEFAULT (current_timestamp AT TIME ZONE 'UTC')

);

CREATE TABLE EventPollOptions (
    option_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    poll_id INT NOT NULL REFERENCES Polls(id),
    location VARCHAR(255),
    start_datetime TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_datetime TIMESTAMP WITHOUT TIME ZONE,

    CHECK (
        (
            -- location only poll --

            start_datetime IS NULL
            AND end_datetime IS NULL  
        )
        OR
        (
            -- poll has start time but no end time --

            start_datetime IS NOT NULL
            AND end_datetime IS NULL
        )
        OR
        (
            -- poll has both start and end time and start < end --

            start_datetime IS NOT NULL
            AND end_datetime IS NOT NULL
            AND start_datetime < end_datetime
        )
    )
);

CREATE TABLE PollSubmissions (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    poll_id INT NOT NULL REFERENCES Polls(id),
    user_id INT NOT NULL REFERENCES Users(id),
    submitted_time TIMESTAMP WITHOUT TIME ZONE DEFAULT (current_timestamp AT TIME ZONE 'UTC'),

    UNIQUE (poll_id, user_id)
);

