CREATE TABLE Semesters(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    semester VARCHAR(10) NOT NULL,
    term_year INT NOT NULL,

    CHECK (semester IN ('fall', 'spring')),
    CHECK (term_year >= 2020 AND term_year < 9999),
    UNIQUE (semester, year)

);

CREATE TABLE AppConfig (
    config_id INT NOT NULL PRIMARY KEY DEFAULT 1,
    current_semester_id INT REFERENCES Semesters(id)
);

CREATE TABLE Users (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    user_type VARCHAR(20) NOT NULL,

    -- typically for players only --
    joined_semester_id INT REFERENCES Semesters(id),
    class_year INT,
    jersey_num INT,

    -- duke users specific --
    duke_email VARCHAR(255) UNIQUE,

    -- external users specific --
    external_email VARCHAR(255) UNIQUE,
    hash_password TEXT,

    is_admin BOOLEAN DEFAULT FALSE,

    CHECK (user_type IN ('player', 'staff', 'alum')),
    CHECK (class_year >= 2020 AND class_year < 9999),
    CHECK (duke_email IS NOT NULL OR external_email IS NOT NULL)

);

CREATE TABLE Executives (
    executive_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INT NOT NULL REFERENCES Users(id),
    position VARCHAR(50) NOT NULL,
    term_start_year INT NOT NULL
);

CREATE TABLE Staff (
    staff_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INT NOT NULL REFERENCES Users(id),
    staff_role VARCHAR(50) NOT NULL,
    active_semester_id INT NOT NULL REFERENCES Semesters(id)
);

CREATE TABLE Events (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    semester_id INT NOT NULL REFERENCES Semesters(id),
    location_name VARCHAR(255) NOT NULL,
    location_address VARCHAR(255),
    event_description TEXT,
    category VARCHAR(30) NOT NULL,
    start_datetime TIMESTAMP,
    end_datetime TIMESTAMP,
    created_by INT REFERENCES Users(id),
    event_status VARCHAR(20) NOT NULL DEFAULT 'tentative',
    created_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    

    CHECK (category IN ('practice', 'tournament', 'game', 'other')), -- game refers to a standalone game --
    CHECK (event_status IN ('tentative', 'scheduled', 'cancelled'))
);

CREATE TABLE UserAvailability (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    semester_id INT NOT NULL REFERENCES Semesters(id),
    user_id INT NOT NULL REFERENCES Users(id),
    day_of_week VARCHAR(10) NOT NULL,
    start_time TIME WITHOUT TIME ZONE NOT NULL,
    end_time TIME WITHOUT TIME ZONE NOT NULL,
    last_updated TIMESTAMP WITHOUT TIME ZONE DEFAULT (current_timestamp AT TIME ZONE 'UTC'),


    CHECK (day_of_week IN ('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday')),
    CHECK (start_time < end_time),
    UNIQUE (semester_id, user_id, day_of_week, start_time, end_time)
);

CREATE TABLE Polls (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    event_id INT NOT NULL REFERENCES Events(id),
    title VARCHAR(255),
    created_time TIMESTAMP WITHOUT TIME ZONE DEFAULT (current_timestamp AT TIME ZONE 'UTC')

);

CREATE TABLE EventPollOptions (
    option_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    poll_id INT NOT NULL REFERENCES Polls(id),
    location_name VARCHAR(255),
    start_datetime TIMESTAMP WITHOUT TIME ZONE,
    end_datetime TIMESTAMP WITHOUT TIME ZONE,

    CHECK (
        (
            -- location only poll --

            start_datetime IS NULL
            AND end_datetime IS NULL  
            AND location_name IS NOT NULL
        )
        OR
        (
            -- poll has start time but no end time --

            start_datetime IS NOT NULL
            AND end_datetime IS NULL
        )
        OR
        (
            -- poll has both start and end time and start < end --

            start_datetime IS NOT NULL
            AND end_datetime IS NOT NULL
            AND start_datetime < end_datetime
        )
    )
);

CREATE TABLE PollSubmissions (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    poll_id INT NOT NULL REFERENCES Polls(id),
    user_id INT NOT NULL REFERENCES Users(id),
    submitted_time TIMESTAMP WITHOUT TIME ZONE DEFAULT (current_timestamp AT TIME ZONE 'UTC'),

    UNIQUE (poll_id, user_id)
);

CREATE TABLE PollSelections (
    submission_id INT NOT NULL REFERENCES PollSubmissions(id),
    option_id INT NOT NULL REFERENCES EventPollOptions(option_id),

    PRIMARY KEY (submission_id, option_id)
);

CREATE TABLE RSVPSubmissions (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    event_id INT NOT NULL REFERENCES Events(id),
    user_id INT NOT NULL REFERENCES Users(id),
    submission_value VARCHAR(10) NOT NULL,
    submitted_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),

    CHECK (submission_value IN ('yes', 'no', 'maybe')),
    UNIQUE (event_id, user_id)
);

CREATE TABLE Practices (
    id INT PRIMARY KEY REFERENCES Events(id),
    practice_type VARCHAR(50) NOT NULL DEFAULT 'regular',

    CHECK (practice_type IN ('regular', 'iq', 'conditioning', 'film', 'other'))
);

CREATE TABLE Tournaments (
    id INT PRIMARY KEY REFERENCES Events(id),
    player_fee DECIMAL(12, 2),
    team_fee DECIMAL(12, 2)
);

CREATE TABLE Games (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    opponent_name VARCHAR(20),
    duke_score INT,
    opp_score INT
);

CREATE TABLE Attendance (
    event_id INT NOT NULL REFERENCES Events(id),
    user_id INT NOT NULL REFERENCES Users(id),
    attended BOOLEAN,

    PRIMARY KEY (event_id, user_id)
);

CREATE TABLE TournamentRegistrations (
    tournament_id INT NOT NULL REFERENCES Tournaments(id),
    user_id INT NOT NULL REFERENCES Users(id),
    payment_status VARCHAR(20) NOT NULL DEFAULT 'unpaid',

    PRIMARY KEY (tournament_id, user_id),
    CHECK (payment_status IN ('paid', 'pending', 'unpaid'))
);

CREATE TABLE DriverResponses (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tournament_id INT NOT NULL REFERENCES Tournaments(id),
    user_id INT NOT NULL REFERENCES Users(id),
    can_drive BOOLEAN NOT NULL,
    seat_capacity INT,
    notes TEXT,
    submitted_time TIMESTAMP WITHOUT TIME ZONE DEFAULT (current_timestamp AT TIME ZONE 'UTC')
);

CREATE TABLE TransportationGroups (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    event_id INT NOT NULL REFERENCES Events(id),
    group_name VARCHAR(100) NOT NULL,
    capacity INT,
    notes TEXT
);

CREATE TABLE TransportationAssignments (
    group_id INT NOT NULL REFERENCES TransportationGroups(id),
    user_id INT NOT NULL REFERENCES Users(id),
    is_driver BOOLEAN, 

    PRIMARY KEY (group_id, user_id)
);

CREATE TABLE Lodgings (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    event_id INT NOT NULL REFERENCES Events(id),
    location_name VARCHAR(100),
    location_address VARCHAR(255),
    notes TEXT
);

CREATE TABLE RoomSpaces (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    location_id INT NOT NULL REFERENCES Lodgings(id),
    space_name VARCHAR(100), -- room name or number --
    capacity INT,
    notes TEXT
);

CREATE TABLE RoomAssignments (
    room_id INT NOT NULL REFERENCES RoomSpaces(id),
    user_id INT NOT NULL REFERENCES Users(id),

    PRIMARY KEY (room_id, user_id)
);

CREATE TABLE AppFeedback (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INT REFERENCES Users(id),
    feedback_message TEXT NOT NULL,
    submitted_time TIMESTAMP WITHOUT TIME ZONE DEFAULT (current_timestamp AT TIME ZONE 'UTC')
);