CREATE TABLE semesters(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    semester VARCHAR(10) NOT NULL,
    term_year INT NOT NULL,

    CHECK (semester IN ('fall', 'spring')),
    CHECK (term_year >= 2020 AND term_year < 9999),
    UNIQUE (semester, term_year)

);

CREATE TABLE app_config (
    config_id INT NOT NULL PRIMARY KEY DEFAULT 1,
    current_semester_id NOT NULL INT REFERENCES semesters(id)
);

CREATE TABLE users (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    user_type VARCHAR(20) NOT NULL,

    -- typically for players only --
    joined_semester_id INT REFERENCES semesters(id),
    class_year INT,
    jersey_num INT,

    -- duke users specific --
    duke_email VARCHAR(255) UNIQUE,

    -- external users specific --
    external_email VARCHAR(255) UNIQUE,
    hash_password TEXT,

    is_admin BOOLEAN DEFAULT FALSE,

    CHECK (user_type IN ('player', 'staff', 'alum')),
    CHECK (class_year >= 2020 AND class_year < 9999),
    CHECK (duke_email IS NOT NULL OR external_email IS NOT NULL)

);

CREATE TABLE executives (
    executive_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INT NOT NULL REFERENCES users(id),
    position VARCHAR(50) NOT NULL,
    term_start_year INT NOT NULL
);

CREATE TABLE staff (
    staff_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INT NOT NULL REFERENCES users(id),
    staff_role VARCHAR(50) NOT NULL,
    active_semester_id INT NOT NULL REFERENCES semesters(id)
);

CREATE TABLE events (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    semester_id INT NOT NULL REFERENCES semesters(id),
    location_name VARCHAR(255) NOT NULL,
    location_address VARCHAR(255),
    event_details TEXT,
    category VARCHAR(30) NOT NULL,
    start_datetime TIMESTAMP,
    end_datetime TIMESTAMP,
    created_by INT REFERENCES users(id),
    event_status VARCHAR(20) NOT NULL DEFAULT 'tentative',
    created_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    

    CHECK (category IN ('practice', 'tournament', 'game', 'other')), -- game refers to a standalone game --
    CHECK (event_status IN ('tentative', 'scheduled', 'cancelled'))
);

CREATE TABLE user_availability (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    semester_id INT NOT NULL REFERENCES semesters(id),
    user_id INT NOT NULL REFERENCES users(id),
    day_of_week VARCHAR(10) NOT NULL,
    start_time TIME WITHOUT TIME ZONE NOT NULL,
    end_time TIME WITHOUT TIME ZONE NOT NULL,
    last_updated TIMESTAMP WITHOUT TIME ZONE DEFAULT (current_timestamp AT TIME ZONE 'UTC'),


    CHECK (day_of_week IN ('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday')),
    CHECK (start_time < end_time),
    UNIQUE (semester_id, user_id, day_of_week, start_time, end_time)
);

CREATE TABLE polls (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    event_id INT NOT NULL REFERENCES events(id),
    title VARCHAR(255) NOT NULL,
    created_time TIMESTAMP WITHOUT TIME ZONE DEFAULT (current_timestamp AT TIME ZONE 'UTC')

);

CREATE TABLE event_poll_options (
    option_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    poll_id INT NOT NULL REFERENCES polls(id),
    location_name VARCHAR(255),
    start_datetime TIMESTAMP WITHOUT TIME ZONE,
    end_datetime TIMESTAMP WITHOUT TIME ZONE,

    CHECK (
        (
            -- location only poll --

            start_datetime IS NULL
            AND end_datetime IS NULL  
            AND location_name IS NOT NULL
        )
        OR
        (
            -- poll has start time but no end time --

            start_datetime IS NOT NULL
            AND end_datetime IS NULL
        )
        OR
        (
            -- poll has both start and end time and start < end --

            start_datetime IS NOT NULL
            AND end_datetime IS NOT NULL
            AND start_datetime < end_datetime
        )
    )
);

CREATE TABLE poll_submissions (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    poll_id INT NOT NULL REFERENCES polls(id),
    user_id INT NOT NULL REFERENCES users(id),
    submitted_time TIMESTAMP WITHOUT TIME ZONE DEFAULT (current_timestamp AT TIME ZONE 'UTC'),

    UNIQUE (poll_id, user_id)
);

CREATE TABLE poll_selections (
    submission_id INT NOT NULL REFERENCES poll_submissions(id),
    option_id INT NOT NULL REFERENCES event_poll_options(option_id),

    PRIMARY KEY (submission_id, option_id)
);

CREATE TABLE rsvp_submissions (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    event_id INT NOT NULL REFERENCES events(id),
    user_id INT NOT NULL REFERENCES users(id),
    submission_value VARCHAR(10) NOT NULL,
    submitted_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),

    CHECK (submission_value IN ('yes', 'no', 'maybe')),
    UNIQUE (event_id, user_id)
);

CREATE TABLE practices (
    id INT PRIMARY KEY REFERENCES events(id),
    practice_type VARCHAR(50) NOT NULL DEFAULT 'regular',

    CHECK (practice_type IN ('regular', 'iq', 'conditioning', 'film', 'other'))
);

CREATE TABLE tournaments (
    id INT PRIMARY KEY REFERENCES events(id),
    player_fee DECIMAL(12, 2),
    team_fee DECIMAL(12, 2),
    tournament_type VARCHAR(50),
    group_transportation_required DEFAULT FALSE;
    lodging_required DEFAULT FALSE;
    registration_deadline TIMESTAMP WITHOUT TIME ZONE,
);

CREATE TABLE games (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    event_id INT REFERENCES users(id),
    opponent_name VARCHAR(20) NOT NULL,
    duke_score INT,
    opp_score INT
);

CREATE TABLE attendance (
    event_id INT NOT NULL REFERENCES events(id),
    user_id INT NOT NULL REFERENCES users(id),
    attended BOOLEAN,

    PRIMARY KEY (event_id, user_id)
);

CREATE TABLE tournament_registrations (
    tournament_id INT NOT NULL REFERENCES tournaments(id),
    user_id INT NOT NULL REFERENCES users(id),
    payment_status VARCHAR(20) NOT NULL DEFAULT 'unpaid',

    PRIMARY KEY (tournament_id, user_id),
    CHECK (payment_status IN ('paid', 'pending', 'unpaid'))
);

CREATE TABLE driver_responses (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tournament_id INT NOT NULL REFERENCES tournaments(id),
    user_id INT NOT NULL REFERENCES users(id),
    can_drive BOOLEAN NOT NULL,
    seat_capacity INT,
    notes TEXT,
    submitted_time TIMESTAMP WITHOUT TIME ZONE DEFAULT (current_timestamp AT TIME ZONE 'UTC')
);

CREATE TABLE transportation_groups (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    event_id INT NOT NULL REFERENCES events(id),
    group_name VARCHAR(100) NOT NULL,
    capacity INT,
    notes TEXT
);

CREATE TABLE transportation_assignments (
    group_id INT NOT NULL REFERENCES transportation_groups(id),
    user_id INT NOT NULL REFERENCES users(id),
    is_driver BOOLEAN DEFAULT FALSE, 

    PRIMARY KEY (group_id, user_id)
);

CREATE TABLE lodgings (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    event_id INT NOT NULL REFERENCES events(id),
    location_name VARCHAR(100),
    location_address VARCHAR(255),
    notes TEXT
);

CREATE TABLE room_spaces (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    location_id INT NOT NULL REFERENCES lodgings(id),
    space_name VARCHAR(100) NOT NULL, -- room name or number --
    capacity INT,
    notes TEXT
);

CREATE TABLE room_assignments (
    room_id INT NOT NULL REFERENCES room_spaces(id),
    user_id INT NOT NULL REFERENCES users(id),

    PRIMARY KEY (room_id, user_id)
);

CREATE TABLE announcements (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    content TEXT NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_by INT REFERENCES users(id),
    pinned BOOLEAN FALSE,
    created_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC')
);

CREATE TABLE plays (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    play_name VARCHAR(255) NOT NULL,
    play_type VARCHAR(20) NOT NULL,
    play_number INT,
    thumbnail_url TEXT NOT NULL,
    animation_url TEXT,
    description TEXT,

    CHECK (play_type IN ('offense', 'defense', 'special teams')),
    UNIQUE (play_type, play_number)
);

CREATE TABLE app_feedback (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INT REFERENCES users(id),
    feedback_message TEXT NOT NULL,
    submitted_time TIMESTAMP WITHOUT TIME ZONE DEFAULT,(current_timestamp AT TIME ZONE 'UTC')
);

-- triggers --

CREATE FUNCTION validate_staff_user() RETURNS TRIGGER AS $$
    BEGIN
        IF (
            SELECT user_type
            FROM users
            WHERE id = NEW.user_id
        ) 
            != 'staff' THEN RAISE EXCEPTION
            'User is not staff.';
        END IF;

        RETURN NEW;

    END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER staff_validation()
BEFORE INSERT OR UPDATE ON staff
FOR EACH ROW
EXECUTIVE FUNCTION validation_staff_user();


